### 20.异常（Exception）

#### 20.1 异常的概述

​         java异常是指在程序中处理逻辑错误的一种机制，这些错误是指一些异常事件（如数组下标越界、除法运算中除数是0，操作的文件的不存在）。

​         异常处理是程序良好的表现，使得出现异常时程序不会出现未知的情况，并能很好的处理它。

​         java程序执行过程如出现异常事件可以生成一个异常类，封装一些异常信息堆栈信息并提交给系统，这个过程称之为抛出异常(```throw Exception```)。对该异常进行处理的代码称为捕获异常(```catch Exception```)。

#### 20.2 异常分类

* ```Error``` 称为错误，jvm抛出，如```OutOfMemoryError```、```StackOverFlowError ```等，一般程序无法对其处理
* ```Exception```所有异常类的父类，其子类定义了各种异常事件，一般需要程序员自己显式的声明或捕获处理
* ```RuntimeException```：运行时异常，特殊的异常，如数组下标越界、空指针，这类异常产品频繁，处理麻烦，jvm会自动检测，程序员可以不必处理。

#### 20.3 异常捕获和处理

​        异常捕获的代码形式：

```java
try {
    //some code maybe throw Exception
} catch(SomeException e1){
    
}catch(SomeException e2){
    
}finally {
    //some code 
}
```

* try代码块包含可能会抛出异常的代码，如果没有异常产生所有catch代码块都不执行

* try后面可以跟一个或多个catch代码块，每个catch代码段声明其处理的一种特定异常并包含处理逻辑

* 当异常发生，程序会终止当前代码行之后的代码，根据异常类型去执行相应catch代码块。当多个catch代码块时，后一个catch的异常不能是前面异常的子类，否则后一个代码块的代码会编译错误

  例子：

  ```java
  
  try {
      String a = null;
      a.equals("null");
  }catch (Exception e){
      //此方法用于打印异常的堆栈内容，对修补bug很有帮助
      e.printStackTrace();
  }catch (NullPointerException e){
  	//第二个catch的异常NullPointerException 是第一个Exception的子类
      //此处编译失败，因为发生空指针异常(NullPointerException)时第一个catch肯定能捕获到
      //两个catch换下顺序则编译通过
  }
  ```

  

* 无论是否发生异常，finally代码块都会被执行。常用来关闭资源，如数据库连接、文件流的关闭等

例子：

```java
import java.io.FileInputStream;
import java.io.IOException;
public class Test{
    public static void main(String[] args){
        FileInputStream in = null;
        try {
            in = new FileInputStream("D:\\test.txt");
            int b = 0;
            b = in.read();
            //循环读取文件内容
            while(b!=-1){
                System.out.println(b);
                b = in.read();
            }
        }catch(IOException e){
            e.printStackTrace();
        }finally{
            //关闭文件流
            if(in!=null){
				try {
                    //关闭时候也会发生异常
                    in.close();
                } catch (IOException e) {
                    //关闭流发生异常我们不做处理
                    e.printStackTrace();
                }
            }
        }
    }
}
```

​        异常捕获后可以不处理，直接抛出异常，然后方法上要```throws```该异常。然后jvm会继续向上抛出，如果调用该方法的代码也没处理则继续向上抛出，如果一直没处理直到jvm然后抛出异常，程序停止运行。

```java
public class Test{
    public static void readFile(String path) throws IOException{
		FileInputStream in = null;
        try {
            in = new FileInputStream(path);
            int b = 0;
            b = in.read();
            //循环读取文件内容
            while(b!=-1){
                System.out.println(b);
                b = in.read();
            }
        }catch(IOException e){
            //此处代码捕获异常确不处理，直接throw，交给调用该方法的代码处理
            throw e;
        }
    }
    
    public static void readFile(String path,boolean append) throws IOException  {
        //此处调用readFile,会抛出异常，
        //如果此处代码还不处理，方法上需要throws IOException 继续往上抛
        readFile(path);
    }
    
    public static void main(String[] args){
        //main方法
        String path="D:\\test.txt";
        boolean append = true;
		try {
            //main方法继续调用，如果此处不catch将直接抛给jvm代码停止运行,后面OK不会打印
            //catch之后代码正常逻辑处理，正常OK打印
            readFile(path,append);
        } catch (IOException e) {
            e.printStackTrace();
        }
        System.out.println("OK");
    }
}
```

#### 20.4 自定义异常

​         自定义异常一般：

* 通过继承```java.lang.Exception```类声明自定义异常
* 在代码适当位置生成自定义异常的实例，并用throw 语句抛出该异常
* 方法声明部分用throws抛出该异常

​        例子：

```java
public class CustomerException extends Exception{
    private String msg;
    public CustomerException(String msg){
        super(msg);
    }
}
```

​        声明并抛出异常：

```java
public void Test{
    public void divide(int a, int b) throws CustomerException{
        if(b==0){
            throw new CustomerException("除数不能为0");
        }
        System.out.println("a除以b:" + (a/b));
    }
    
    public static void main(String[] args){
        Test t = new Test();
        try {
            t.divide(10,0);
        }catch(CustomerException e){
            e.printStackTrace();
        }
    }
}
```

例子大家自己编译运行。

**重写方法时需要与被重写方法抛出异常类型一直或者不抛出异常**

